train_dataset_name: "./data/train_dataset_eating_2.csv"
test_dataset_name: "./data/test_dataset_eating_2.csv"
test_label_name: "./data/test_label_eating_2.csv"

answer_label_name: "./answer/eating_2_model_with_labels.csv"
model_name: "./save_models/model_eating_2.pkl"
answer_csv_name: "./answer/eating_2_model_yzt.csv"

label: 3
