train_dataset_name: "./data/train_dataset_impedance_1.csv"
test_dataset_name: "./data/test_dataset_impedance_1.csv"
test_label_name: "./data/test_label_impedance_1.csv"

answer_label_name: "./answer/impedance_1_model_with_labels.csv"
model_name: "./save_models/model_impedance_1.pt"
answer_csv_name: "./answer/impedance_1_model_yzt.csv"

label: 5
