train_dataset_name: "./data/train_dataset_lyh_im.csv"
test_dataset_name: "./data/test_dataset_lyh_im.csv"
test_label_name: "./data/test_label_lyh_im.csv"

answer_label_name: "./answer/lyh_im_model_with_labels.csv"
model_name: "./save_models/model_lyh_im.pkl"
answer_csv_name: "./answer/lyh_im_model.csv"

label: 5
