train_dataset_name: "./data/train1.csv"
test_dataset_name: "./data/testA_answer.csv"
test_label_name: "./data/testA1.csv"

answer_label_name: "./answer/train_model_with_labels.csv"
model_name: "./save_models/model_train.pkl"
answer_csv_name: "./answer/model_train.csv"

label: 5
