train_dataset_name: "./data/train_dataset_yzt_2.csv"
test_dataset_name: "./data/test_dataset_yzt_2.csv"
test_label_name: "./data/test_label_yzt_2.csv"

answer_label_name: "./answer/yzt_2_model_with_labels.csv"
model_name: "./save_models/model_yzt_2.pkl"
answer_csv_name: "./answer/yzt_2_model.csv"

label: 5
