train_dataset_name: "./data/200.csv"
test_dataset_name: "./data/test_dataset_yzt_draw.csv"
test_label_name: "./data/test_label_yzt_draw.csv"

answer_label_name: "./answer/yzt_draw_model_with_labels.csv"
model_name: "./save_models/model_yzt_draw.pkl"
answer_csv_name: "./answer/yzt_draw_model.csv"

label: 5
