train_dataset_name: "./data/train_dataset_zxy_im.csv"
test_dataset_name: "./data/test_dataset_zxy_im.csv"
test_label_name: "./data/test_label_zxy_im.csv"

answer_label_name: "./answer/zxy_im_model_with_labels.csv"
model_name: "./save_models/model_zxy_im.pkl"
answer_csv_name: "./answer/zxy_im_model.csv"

label: 5
