train_dataset_name: "./data/train_dataset_zxy_im2.csv"
test_dataset_name: "./data/test_dataset_zxy_im2.csv"
test_label_name: "./data/test_label_zxy_im2.csv"

answer_label_name: "./answer/zxy_im2_model_with_labels.csv"
model_name: "./save_models/model_zxy_im2.pkl"
answer_csv_name: "./answer/zxy_im2_model.csv"

label: 5
